name: 🚀 Deploy on push to main

on: 
  push:
    branches:    
      - main 

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest


    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📝 Set environment variables
      run: |
        echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env
        echo "VITE_URL=${{ secrets.VITE_URL }}" >> .env
        
    - name: 🔧 Install dependencies and build
      run: |
        npm install
        npm run build

    - name: List output files
      run: find dist/ -print

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          local-dir: dist/
          exclude: |
            **/.git**
            **/.git*/**
            **/node_modules/**
            **/.**
